### ISSUE TITLE
Module request: ETC EOS Lighting Desks

### ISSUE THREAD

**Issue by romanivich** [bitfocus/companion-module-etc-eos#1]
**Describe the feature**
Communication With ETC Lighting Desks and Offline Software

**Is this platform dependent (windows, mac, ..)?**
Mac and Windows

**If documentation is required to implement, do you know where to find it?**
https://www.etcconnect.com/Products/Consoles/Eos-Family/

**Usecases**
To allow multiple actions on the deck to be combined onto one button to speed up programming sessions.

**Comment by krocheck** [comment]
Module has been implemented.
