### ISSUE TITLE
TCP 1.1

### ISSUE THREAD

**Issue by sstaub** [bitfocus/companion-module-etc-eos#11]
Can you add support for SLIP (TCP 1.1)?

**Comment by sstaub** [comment]
With version 3.x there is a third party TCP port on 3037 (instead of 3032) using SLIP

**Comment by n9yty** [comment]
@sstaub I have added a toggle in the configuration for the 'etc-eos' connection to toggle SLIP. If SLIP is off, it uses port 3032, if SLIP is on it will use port 3037 with SLIP.

**Comment by sstaub** [comment]
Does work with 2.0.5
