### ISSUE TITLE
Convert to v3 format?

### ISSUE THREAD

**Issue by n9yty** [bitfocus/companion-module-etc-eos#19]
Unsure if this is unmaintained or not, but is there any plan to update this to V3 format? I was looking at extending it a bit, but not sure I understand all the changes needed to move to V3.

**Comment by josephdadams** [comment]
Go for it. https://github.com/bitfocus/companion-module-base/wiki/Upgrading-a-module-built-for-Companion-2.x

It’s rather straightforward. Tag me when you have a pull request and I’ll review it.

**Comment by n9yty** [comment]
I've started working on it, but some quirk isn't quite straightforward, and I'm having a hard time getting anything logged. I don't know JS that well to begin with, but it seems like this.log('debug', 'string') should get dumped into the log in the web viewer but it isn't. That is slowing things  down. LoL   But I do have the framework converted over, and I see from EOS that it is getting a connection but then dropping for some reason and without logging I'm rather blind.

**Comment by josephdadams** [comment]
If you’re not running a nodejs development environment (which is no longer necessary just for module development), try looking in the console log output. It’s the >_ icon next to the module config in Connections.

If you can commit your code somewhere, I’m happy to help take a look.

**Comment by n9yty** [comment]
Thanks, I'll try to get as  far as I can to give something back, but if I get hopelessly stuck I'll post what I have online. Thanks!

**Comment by n9yty** [comment]
Have a look, it probably isn't so much of a  pull request as a replacement for v3 as the structure is quite different.

https://github.com/n9yty/companion-module-etc-eos

I also tried to rework for #18 to fix cue intensity and #16 to expose encoder wheel values.

**Comment by josephdadams** [comment]
Can you submit it as a PR to this repo so I can leave comments/review?

**Comment by n9yty** [comment]
If I can figure that out....

**Comment by josephdadams** [comment]
I believe in you
