### ISSUE TITLE
OSC sending twice?

### ISSUE THREAD

**Issue by pascals99** [bitfocus/companion-module-etc-eos#2]
When i send a osc message to the lighting desk ETC eos or to OSCulator the message is coming in twice. Is there a way to send it only when the value goes from 0 to positive ?

**Comment by n9yty** [comment]
I have been doing some work on this module, I have never seen this happen. Is this old? Can you duplicate it? My work is in the 3.0 very recent betas.

**Comment by n9yty** [comment]
Not able to reproduce using the current release.
