### ISSUE TITLE
Some Cue data are not correct updated

### ISSUE THREAD

**Issue by sstaub** [bitfocus/companion-module-etc-eos#28]
After commands like "Goto Cue Out", "Goto Cue 0" or at the end of the list,
some cue data are not updated correctly.
This are the data before "Goto Cue 0" which is normally sent:
<img width="816" alt="Bildschirmfoto 2023-06-14 um 09 18 29" src="https://github.com/bitfocus/companion-module-etc-eos/assets/6450325/d1bbf7ca-d84a-49fc-904a-ba359a00030a">
With "Goto Cue 0" EOS send an empty string in `/eos/out/active/cue/text`  `/eos/out/previous/cue/text`  but not in`/eos/out/pending/cue/text`
<img width="816" alt="Bildschirmfoto 2023-06-14 um 09 18 40" src="https://github.com/bitfocus/companion-module-etc-eos/assets/6450325/297f61aa-facb-4d49-9a9d-4bfb1a414c3a">
So the cue data list and number must cleared for previous and active cue. In the moment you can see in the snapshot of Streamdeck+, that the displayed data are wrong. The pending cue data is correct.
<img width="228" alt="Bildschirmfoto 2023-06-14 um 09 34 26" src="https://github.com/bitfocus/companion-module-etc-eos/assets/6450325/b70f8184-cc02-4d51-a5fc-8b39f7fff191">

**Comment by n9yty** [comment]
@sstaub Thank you for your continued testing/feedback.

I think I have the previous cue clearing handled, but the active cue is giving me problems. For previous cue, I see the OSC message /eos/out/previous/cue with no arguments, and that is a clear signal to clear that. However, /eos/out/active/cue never is sent without parameters, it is sent with the float value, always, at least from what I am testing.

If you can document a case of EOS sending an OSC update that can be used to know to clear the active cue list/number I would be glad to put it in.

**Comment by sstaub** [comment]
If the first char of the string is "0" there is no active cue, also if the string is completely empty (I can remember that there is a state when this happen)

**Comment by n9yty** [comment]
Thank you for that, it is unfortunate they don't send the data in a consistent way. {smile}  I see in that case for the /eos/out/active/cue/text the first parameter is missing but it leaves a space and the value is 0.0 when fully out and I think I can work with that. It is better than not trying to detect it at all.

In testing, they behave as expected when stepping through cues, and when using GoToCue 0 or GoToCue Out when the cue progress hits 100% the active cue list/number are set to blank.

That should be the desired behavior, right?

**Comment by sstaub** [comment]
Yes, you are right.
