### ISSUE TITLE
Feedback?

### ISSUE THREAD

**Issue by mysecretstache** [bitfocus/companion-module-etc-eos#3]
It would be great if we can receive feedback info from EOS. EOS can be polled for show information, but it also sends status on a regular basis over OSC

Useful feedback for companion
Soft Keys Labels:
/eos/out/softkey/<1-6> <Softkey label string>

Current Show Name
/eos/out/show/name <showfile name string>

Currrent/next cue info
/eos/out/active/cue
/eos/out/pending/cue

**Comment by SteveTherrien** [comment]
That'd be a great thing to add. Companion calls them "Dynamic Variables" (with "Feedbacks" being something different).

This is what I've been able to add so far:

**List of dynamic variables**

| Variable                        | Description                      | Current value  |
| ------------------------------- | -------------------------------- | -------------- |
| $(etc-eos:cue_active_list)      | The active cue list number       | 1              |
| $(etc-eos:cue_active_num)       | The active cue number            | 20.2           |
| $(etc-eos:cue_active_label)     | The active cue label             | Introduction   |
| $(etc-eos:cue_active_duration)  | The active cue duration          | 5.0            |
| $(etc-eos:cue_active_intensity) | The active cue intensity percent | 100%           |
| $(etc-eos:cue_pending_list)     | The pending cue list number      | 1              |
| $(etc-eos:cue_pending_num)      | The pending cue number           | 20.3           |
| $(etc-eos:cue_pending_label)    | The pending cue label            | Welcome guest  |
| $(etc-eos:cue_pending_duration) | The pending cue duration         | 5.0            |
| $(etc-eos:show_name)            | The name of the show             | Companion test |
| $(etc-eos:softkey_label_1)       | Soft key 1's label           | Address        |
| $(etc-eos:softkey_label_2)       | Soft key 2's label           | Fader          |
| $(etc-eos:softkey_label_3)       | Soft key 3's label           | Snapshot       |
| $(etc-eos:softkey_label_4)       | Soft key 4's label           |                |
| $(etc-eos:softkey_label_5)       | Soft key 5's label           | Fader Control  |
| $(etc-eos:softkey_label_6)       | Soft key 6's label           | Page Subs      |
| $(etc-eos:softkey_label_7)       | Soft key 7's label           | Preview        |
| $(etc-eos:softkey_label_8)       | Soft key 8's label           |                |
| $(etc-eos:softkey_label_9)       | Soft key 9's label           | Offset         |
| $(etc-eos:softkey_label_10)      | Soft key 10's label          |                |
| $(etc-eos:softkey_label_11)      | Soft key 11's label          |                |
| $(etc-eos:softkey_label_12)      | Soft key 12's label          | Color Path     |

_Soft keys 7-12 are the alternate states for 1-6 when you press {More SK}._

----

I'll spend some more time on it this week.

**Comment by mysecretstache** [comment]
Thanks!!!

Let me know if I can be of help.

I'm pretty new to Companion, How can I use these "Dynamic Variables"? The use case I'm thinking, is a SM remote, where above the GO button, the Pending Cue number is displayed.

**Comment by SteveTherrien** [comment]
Thanks for the offer :smile:

You can read up on dynamic variables at https://github.com/bitfocus/companion/blob/master/documentation/gettingstarted.md#dynamic-variables. They're really simple to use, just include the variable in a button's text:

![dynamic_variables](https://user-images.githubusercontent.com/9618303/75213381-c0a74d00-573e-11ea-8262-28568c368012.gif)

Here I have three buttons. These are their labels with the dynamic variables:
3.2: `Live Q:\n$(etc-eos:cue_active_num)\n$(etc-eos:cue_active_label)`
3.3: `Stop/\nBack`
3.4: `Go next\n$(etc-eos:cue_pending_num)\n$(etc-eos:cue_active_intensity)`

(`\n` is just a way of forcing a newline into a button)

**Comment by SteveTherrien** [comment]
Quick update:

I'm also adding support for true Feedbacks in Companion, so you can style buttons according to whether a cue is active or pending.

![feedbacks](https://user-images.githubusercontent.com/9618303/75616602-d1bdd880-5b07-11ea-8647-7c1090f1aaf5.gif)
