### ISSUE TITLE
Path to pictures in Help.md

### ISSUE THREAD

**Issue by sstaub** [bitfocus/companion-module-etc-eos#32]
The path to the configuration pictures seems broken. If it will work I can do some updated pics and advices in the Help.md.

**Comment by n9yty** [comment]
Ok, a little mess up with git but it should be in there now in the pending pull request.

**Comment by n9yty** [comment]
@sstaub You could look at the working version here and suggest changes/updates that I could include:

https://github.com/n9yty/companion-module-etc-eos/tree/cues_wheels
