### ISSUE TITLE
Request: Specific channel intensity as variable

### ISSUE THREAD

**Issue by ATCUSER1** [bitfocus/companion-module-etc-eos#37]
(I'm new to both companion and Github so I might be missing something.) 

I simply would like a button to display the intensity of a chosen channel. Not the currently selected channel, but a specified channel. 

I can see options for cue intensity or the current in the list of $ Variables , just nothing for the above.

**Comment by n9yty** [comment]
@ATCUSER1 I don't believe this would be possible given the way that EOS and Companion interact. It is very much about state chan ge information, so if it is not the active channel EOS doesn't send information about it. I have spent a bit of time looking into this, but in the end have come up with nothing promising. I'm going to mark this as not planned. If some future change in ETC EOS makes it possible, or I stumble across something I haven't found yet, I'll come back to it.

**Comment by ATCUSER1** [comment]
That's unfortunate. I will contact ETC to see if they can help. I know it is possible with Crestron devices, so I'm quietly hoping there is a way.

**Comment by ATCUSER1** [comment]
@n9yty Thank-you for the reply. That's unfortunate. I will contact ETC to see if they can help. I know it is possible with Crestron devices, so I'm quietly hoping there is a work around.
