### ISSUE TITLE
Feedbacks not working in ETC: EOS v2.0.6

### ISSUE THREAD

**Issue by willtb** [bitfocus/companion-module-etc-eos#38]
Software versions:
Companion v3.0.1
ETC: EOS v2.0.6

The following feedbacks cannot be configured correctly:
etc-eos: When cue is pending
etc-eos: When cue is active
etc-eos: When cue is the previous cue

The issue is that in the feedback configuration GUI, the textboxes for cue list and cue number are "tethered" or "mirrored". This means entering a number in the cue list textbox will set the same value in the cue number textbox and vice versa. For example, entering cue list as "1" will overwrite the value in cue number as "1" and entering cue number as "100" will overwrite the value in cue list to "100".
I can confirm that this issue did not occur in pre v3 versions of Companion (eg 2.4.1 and 2.4.2) so must have been introduced during a module update.

WORKAROUND
As a workaround, I am using the module variables directly to provide feedback. In the above case, checking the values of cue_active_list and cue_active_num within an internal: Variable: Check value feedback.

Please let me know if more information is required to investigate this.

Thanks!

**Comment by sstaub** [comment]
Did you tried a newer EOS software version? v2.0.6 is very very old.
it recommended for EOS v.3.2.4 or v2.9.3 (for WinXP consoles).

**Comment by willtb** [comment]
Hello Stephan,

Thanks for your message.

Sorry for the confusion, this isn’t the version of the EOS software but the
Companion EOS module version. I’m not sure of the target system version as
it’s a remote puck unit but it is a recent purchase. I’ll test a local EOS
copy on my PC to verify against a known version.

I’m not great at JavaScript but may have spotted the error in the EOS
module feedback file where the cue list and cue number controls appear to
share the same identity tag. I’m not confident in git so won’t try updating
anything myself. When I’m back at my computer I’ll do some more testing and
will update the issue.

Many thanks,

Will

**Comment by n9yty** [comment]
@willtb Can you share some more details? I know @sstaub has tested it quite a bit and it seemed the feedbacks were working properly.

**Comment by willtb** [comment]
@n9yty many thanks for the prompt response and resolution! I'll give the updated build a go.
