### ISSUE TITLE
Console user -1

### ISSUE THREAD

**Issue by JWilsonLX** [bitfocus/companion-module-etc-eos#4]
Perhaps this is implemented and I’m missing it, but I can’t see to get companion to function as the Eos “console user.” This user triggers OSC messages as whatever user the target device is, and is accessed by sending messages as user -1. When I set the companion user ID to -1, I see messages sent as user 1.

**Comment by SteveTherrien** [comment]
Right now the module only accepts positive User IDs, but I'm currently working an upgrade so I'll be sure this gets addressed along with that.
