### ISSUE TITLE
[Question] Blackout Button

### ISSUE THREAD

**Issue by kernelstearns** [bitfocus/companion-module-etc-eos#5]
This is more of a general OSC question, but I cannot figure out how to enable/disable blackout via this module.  Any ideas?

**Comment by SteveTherrien** [comment]
No, not that I'm away of, but I've updated the module (commit a6994643c834719af05a1a421fccb89f31c7f0da) with a new action to toggle the blackout button (uses OSC command `/eos/key/blackout`). Once Companion updates to include this change, use the new `Key: Blackout` action.

I don't see a way to set it to a specific state or a way to change the grandmaster's level. This is probably all that can be done unless someone knows better OSC commands.
