### ISSUE TITLE
Can't sent EOS 

### ISSUE THREAD

**Issue by Obvious78** [bitfocus/companion-module-etc-eos#9]
Hi there,
Recently I discovered that I still have some EOS in myetherwallet / EOS voter / Anchor Wallet.
Problem is: I can see my 40 EOS with a balance of around €260. But when trying to sent my EOS to another exchange, it'll only let me sent EOS tokens that has a balance of 0,0001 EOS. Please help me with this issue?

**Comment by krocheck** [comment]
Hi @Obvious78, this is for support related to the Companion software that controls ETC Lighting Consoles, not any crypto currency.  We won't be able to assist you.

**Comment by Obvious78** [comment]
Ow sorry. I've been looking for help for my issue.
